### ISSUE TITLE
Permission denied after Processing

### ISSUE THREAD

**Issue by TheClassyTurkey** [Haoming02/sd-webui-old-photo-restoration#1] opened 2023-12-06 16:57 UTC
I am receiving this permissions error after trying to process the image. I believe the issue is that it is unable to create the folder for the output. I am running this on a mac environment.

> /Documents/SD-Main/stable-diffusion-webui/venv/bin/activate: Permission denied
Traceback (most recent call last):
File "/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/Documents/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/bop.py", line 81, in bop
    results = detect_new_results(final_output, cache)
  File "/Documents/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/bop.py", line 41, in detect_new_results
    new_files = {f: os.path.getmtime(os.path.join(output_folder, f)) for f in os.listdir(output_folder)}
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/SD-Main/stable-diffusion-webui/outputs/old-photo-restoration/12.06-10.49.40/final_output'

**Comment by Haoming02** [comment] 2023-12-07 02:28
Please check if the issue has been fixed~

**Comment by Haoming02** [comment] 2023-12-07 02:37
Oh wait. I see the issue now...
It's not related to the output path.

> /Documents/SD-Main/stable-diffusion-webui/venv/bin/activate: Permission denied

It wasn't able to start the process, so the output path was not generated to being with...

**Comment by ali0une** [comment] 2023-12-09 12:37
Same issue here : venv/bin/activate: Permission denied.
A1111 on Debian. 

Yes A1111 uses a venv to run, it is located at stable-diffusion-webui/venv
To run a python command using this venv you have to :
`source stable-diffusion-webui/venv/bin/activate`
then : 
`python whatever/script.py`

if i open a terminal
```
cd stable-diffusion-webui/repositories/BOP-BtL 
source A1111/venv/bin/activate 
python /whatever/stable-diffusion-webui/repositories/BOP-BtL/run.py --GPU 0 --input_folder /whatever/input_folder --output_folder /whatever/stable-diffusion-webui/outputs/old-photo-restoration
```

it works.

But it doesn't with the current code in the extension.
i don't know how to tell your bop.py script to do what i can do manualy.
Maybe there is a way using A1111 built in fonctionalities.

**Comment by Haoming02** [comment] 2023-12-09 14:03
Please try the new version
Now I also added `source` in the begining of the commands

**Comment by Haoming02** [comment] 2023-12-09 16:20
Hmm, my command is 
```py
['source', '~webui/venv/bin/activate', '&&', 'python', 'run.py', ...]`
though

**Comment by Haoming02** [comment] 2023-12-09 16:22
Again, the issue is not on the path. The path will exist if it launches the script properly.
Did you still get **`Permission denied`** error?

**Comment by ali0une** [comment] 2023-12-09 17:09
> Hmm, my command is
> 
> ```python
> ['source', '~webui/venv/bin/activate', '&&', 'python', 'run.py', ...]`
> ```
> 
> though

Maybe there is another way to execute the /whatever/stable-diffusion-webui/repositories/BOP-BtL/run.py script from an extension.
i don't know, my python knowledge is very limited.


> Again, the issue is not on the path. The path will exist if it launches the script properly. Did you still get **`Permission denied`** error?

Yes just like i said in https://github.com/Haoming02/sd-webui-old-photo-restoration/issues/1#issuecomment-1848431332

**Comment by Haoming02** [comment] 2023-12-11 01:54
*Reddit [Discussion](https://www.reddit.com/r/localdiffusion/comments/18f33fb/anyone_has_knowledge_about_executing_a_python/)*

**Comment by jjlee** [comment] 2023-12-11 21:30
Does this help?

```
import subprocess
import shlex

def run_in_venv_on_unix(virtualenv_path, command):
    subprocess.check_call(["bash", "-c", f'source {shlex.quote(virtualenv_path)}/bin/activate && exec "$@"', "wrapper_script"] + command)
```

**Comment by ali0une** [comment] 2023-12-12 17:03
@jjlee many thanks for your input.

i'd like to integrate this to @Haoming02 code but i have to define some variables like **virtualenv_path** and **wrapper_script** right?
i guess command are the parameters given to the run.py script, wrapper_script the run.py script itself, right?
What about **virtualenv_path**? is it the absolute path to the venv?

**Comment by jjlee** [comment] 2023-12-13 00:21
You can call `run_in_venv_on_unix` passing whatever virtualenv path and whatever unix command you like, yes:

```
run_in_venv_on_unix("/path/to/my/virtualenv_dir", ["python", "whatever.py", "some", "arguments"])
```

Since `virtualenv_path` is passed to bash as part of the shell command (the next item in the list after the `-c`), bash will do whatever it normally does with paths you pass to shell builtin `source` -- which means if you pass a relative path, it will be treated as relative to the bash process' current working directory.

`"wrapper_script"` is just a listeral string, which is just a placeholder: it could be `"eager_frogs"` if you prefer.  Why?  It's not very important and quite confusing (try playing around with this in both python and bash to get it), but have a look at `man bash` -- quoting from that:

```
       -c        If the -c option is present, then commands are read from the first non-option argument command_string.  If there are arguments after the command_string, the first argument is assigned to $0 and any  remaining  argu‐
                 ments are assigned to the positional parameters.  The assignment to $0 sets the name of the shell, which is used in warning and error messages.
```

`$0` in bash is the equivalent of python's `sys.argv[0]`, so in that sense it's the "first argument" of the unix command that launched bash.  It's worth understanding that shell commands (what bash -c takes as its argument) are strings, but "unix commands" (what the `execve` system call takes as an argument -- take a look at `man -S2 execve`) are arrays.  That "first item" of a unix command array is special, and in fact `execve (2)` handles it as a first argument separate from the rest of the array for that reason: what you pass as that argument is the path of the program you're executing (so in `bash my-script.sh foo bar`, the code in `my-script.sh` sees `$0` as `my-script.sh`. and `$@` is the rest -- in python syntax `["foo", "bar"]`).  When you call `bash -c`, bash doesn't have a great choice of string to use for `$0` (because it's an inline script, there's no `my-script.sh` filename to pass to `exec`'s first argument).  So bash allows you to specify whatever string you like to pass!  (I would guess `bash -c` doesn't actually call `execve`, but just interprets the shell command you pass with `$0` set to what you asked it to set)

**Comment by Haoming02** [comment] 2023-12-13 04:02
Hello, please check out the [dev](https://github.com/Haoming02/sd-webui-old-photo-restoration/tree/dev) branch~

I now run the functions directly instead of trying to call the scripts. Right now only the first step is implemented. Please test if it works correctly now.

Delete the extension folder first and clone the new `dev` branch.

Then move the `checkpoints` folders and the `landmarks.dat` file from inside the `BOP-Bt:` folder in `repositories`, to the new extension folder. *(The structure is exactly the same)* *(But only move the models, as I have modified the scripts)*

**Comment by ali0une** [comment] 2023-12-17 09:11
@jjlee once again, many thanks for your input, that's **very** interesting! i'm copy/pasting this in a .txt file in my tips folder right now!

@Haoming02 the dev branch still fails with exact same errors.
i persist to think you need to think about what @jjlee proposes as i'm pretty sure it's an issue related to how the command is launched via the extension.

i'll use the original repo of BOPBTL with a venv in command line for the moment as this works nice.
Would have been nice to have it integrated and working into A1111 with Linux.

**Comment by Haoming02** [comment] 2023-12-17 12:17
@ali0une 
The **dev** branch isn't even using `process` anymore.
Are you sure you switched correctly?

**Comment by Haoming02** [comment] 2023-12-17 13:38
Did you disable `Scratch` ?

**Comment by ali0une** [comment] 2023-12-17 13:47
> Did you disable `Scratch` ?

No ... disabled Scratch and it works (without global restoration btw)!
```
Mapping: You are using the mapping model without global restoration.
Now you are processing some_pic.jpg
```

**Comment by Haoming02** [comment] 2023-12-17 14:45
Aye finally...
Now I just need to implement the rest of the features~

**Comment by Haoming02** [comment] 2023-12-19 03:38
Should be fixed on the `main` branch now~

**Comment by TheClassyTurkey** [comment] 2023-12-19 22:51
Thank you for your continued work on this. I upgraded my main branch to the latest release and am now getting this error with no options checked

```
Running Stage 1: Overall restoration
Traceback (most recent call last):

  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/whatever/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/main_function.py", line 142, in bop
    final_output = core_functions(input_path, output_path, gpu_id, scratch, hr, face_res)
  File "/whatever/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/main_function.py", line 67, in core_functions
    global_test(args, GLOBAL_CHECKPOINTS_FOLDER)
  File "/whatever/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Global/test.py", line 97, in global_test
    opt = TestOptions().parse(custom_args, save=False)
  File "/whatever/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Global/options/base_options.py", line 358, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/whatever/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

```

**Comment by Haoming02** [comment] 2023-12-20 02:02
The latest [commit](https://github.com/Haoming02/sd-webui-old-photo-restoration/commit/40974b266d0362d5aa57a50514e6172bb0389d83) now handles the cases where no CUDA-compatible GPU is available~

**Comment by Haoming02** [comment] 2024-01-03 01:54
Assuming the issue has been fixed.
Do open this Issue again if it's related to running on non-Windows environment~

**Closed by Haoming02** 2024-01-03 01:54 UTC

**Comment by TheClassyTurkey** [comment] 2024-01-03 19:47
Apoligies, I was busy over the holiday and just saw you had tried to fix this issue. Reopening issue as it appears to be still related to non-windows enviroments.

I pulled the latest commit and am now seeing this error.

```
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
directory of testing image: /somelocation/Documents/photorestore-test
processing photo-restoration-example-001-before.jpg
Traceback (most recent call last):
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/somelocationDocuments/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/main_function.py", line 142, in bop
    final_output = core_functions(input_path, output_path, gpu_id, scratch, hr, face_res)
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/main_function.py", line 74, in core_functions
    global_detection(args)
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Global/detection.py", line 179, in global_detection
    main(config)
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Global/detection.py", line 146, in main
    scratch_image_scale = scratch_image_scale.to(config.GPU)
  File "/somelocation/Documents/SD-Main/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```



Another thing I noticed was that this message was displayed every time I launch SD. I know there is another issue open related to the "Installing requirements" message appearing.

```
Python 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing Requirements for Bringing-Old-Photos-Back-to-Life...
Installing Old-Photo-Restoration Requirement: scikit-image
Installing Old-Photo-Restoration Requirement: PyYAML
Installing Old-Photo-Restoration Requirement: opencv-python
```
